export const routes = {
  WELCOME_SCREEN: "WelcomeScreen",
  SIGNUP_SCREEN: "SignUpScreen",
  LOGIN_SCREEN: "LoginScreen",
  FORGOT_PASSWORD: "ForgotPasswordScreen",
  PHONE_PROMPT: "PhonePromptScreen",
  PHONE_VERIFICATION: "PhoneVerificationScreen",
  GEO_LOCATION_PROMPT: "GeoLocationPromptScreen",
  GEO_LOCATION_MANUAL: "GeoLocationManualScreen",
  HOME_TAB: "Home",
  MANAGER_HOME_TAB: "Manager Home",
  MANAGER_HOME: "ManagerHomeStackScreen",
  PROFILE_TAB: "Profile",
  FAVORITES: "Favourites",
  NOTIFICATIONS: "Notifications",
  CART_TAB: "Cart",
  RESTAURANT: "RestaurantTabScreen",
  HOME: "HomeStackScreen",
  DETAIL: "DetailStackScreen",
  CART: "CartStackScreen",
  CHECKOUT: "CheckoutStackScreen",
  DELIVERY: "DeliveyStackScreen",
  DELIVERY_ADDRESSES: "DeliveyAdressesScreen",
  CARDS: "CardsScreen",
  ORDERS: "Orders",
  PROFILE: "ProfileStackScreen",
  EDIT_PROFILE: "EditProfileScreen",
  RESTAURANT_DETAIL: "RestaurantDetailStackScreen",
  DEBUG: "Debug",
};
